import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const rootDir = path.join(__dirname, '..');

// Читаем базовую версию из VERSION.json
const versionFile = path.join(rootDir, 'VERSION.json');
const versionData = JSON.parse(fs.readFileSync(versionFile, 'utf-8'));

// Получаем текущий timestamp для patch версии
const buildNumber = Math.floor(Date.now() / 1000) % 10000;

// Формируем полную версию
const fullVersion = `${versionData.major}.${versionData.minor}.${buildNumber}`;

// Обновляем package.json с полной версией
const packageFile = path.join(rootDir, 'package.json');
const packageData = JSON.parse(fs.readFileSync(packageFile, 'utf-8'));
packageData.version = fullVersion;
fs.writeFileSync(packageFile, JSON.stringify(packageData, null, 2) + '\n');

// Обновляем версию в манифестах
const chromiumManifestPath = path.join(rootDir, 'manifests', 'manifest.chromium.json');
const chromiumManifest = JSON.parse(fs.readFileSync(chromiumManifestPath, 'utf-8'));
chromiumManifest.version = fullVersion;
fs.writeFileSync(chromiumManifestPath, JSON.stringify(chromiumManifest, null, 2) + '\n');

const firefoxManifestPath = path.join(rootDir, 'manifests', 'manifest.firefox.json');
const firefoxManifest = JSON.parse(fs.readFileSync(firefoxManifestPath, 'utf-8'));
firefoxManifest.version = fullVersion;
fs.writeFileSync(firefoxManifestPath, JSON.stringify(firefoxManifest, null, 2) + '\n');

// Создаем версию для встроенной константы в плагин
const versionModule = `// This file is auto-generated by scripts/version.js during build
export const VERSION = '${fullVersion}';
export const VERSION_CHECK_URL = 'https://api.github.com/repos/YOUR_REPO/releases/latest';
`;
const versionModulePath = path.join(rootDir, 'src', 'core', 'version.ts');
fs.writeFileSync(versionModulePath, versionModule);

console.log(`✓ Version set to: ${fullVersion}`);
console.log(`✓ package.json updated`);
console.log(`✓ manifest.chromium.json updated`);
console.log(`✓ manifest.firefox.json updated`);
console.log(`✓ version.ts created`);
